"""CLI-level tests for ``aegis init``.

The wizard is interactive; we drive it by patching the providers list
(so it doesn't depend on which CLIs are installed) and feeding stdin
through CliRunner's ``input=`` argument. CliRunner runs typer in-process
so monkeypatching keeps the wizard's Console reading from the runner's
stdin.
"""
from typer.testing import CliRunner

from aegis.cli import app
from aegis.init_wizard import ProviderSpec

runner = CliRunner()


# A deterministic "Claude only" provider catalog so tests don't depend
# on what's installed on the box running them.
def _patch_claude_only(monkeypatch):
    fixture = [
        ProviderSpec(
            name="claude-code", cli="claude", cls_name="ClaudeCode",
            model_shortlist=("opus", "sonnet", "haiku"),
            permission_choices=("read", "write", "full", "auto"),
            default_permission="auto", has_effort=True, available=True,
        ),
        ProviderSpec(
            name="gemini", cli="gemini", cls_name="GeminiCLI",
            model_shortlist=("gemini-3-flash-preview", "gemini-3.1-pro"),
            permission_choices=("read", "write", "full", "auto"),
            default_permission="full", has_effort=False, available=False,
        ),
        ProviderSpec(
            name="opencode", cli="opencode", cls_name="OpenCode",
            model_shortlist=("opencode/kimi-k2.6", "opencode/glm-5.1"),
            permission_choices=("read", "write", "full", "auto"),
            default_permission="full", has_effort=False, available=False,
        ),
    ]
    monkeypatch.setattr(
        "aegis.init_wizard.detect_providers",
        lambda which=None: fixture)


def test_init_refuses_when_upstream_aegis_py_exists(tmp_path, monkeypatch):
    """find_project_root catches an upstream config; refuse without
    --force, suggest --force in the message."""
    (tmp_path / ".aegis.py").write_text("# upstream\n")
    sub = tmp_path / "subdir"
    sub.mkdir()
    monkeypatch.chdir(sub)
    result = runner.invoke(app, ["init"])
    assert result.exit_code != 0
    assert "already configured" in result.output
    assert "--force" in result.output


def test_init_refuses_when_local_aegis_py_exists(tmp_path, monkeypatch):
    """Local file in cwd (with no upstream) — same refuse-without-force."""
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".aegis.py").write_text("# local\n")
    monkeypatch.setenv("HOME", str(tmp_path / "no_home"))
    result = runner.invoke(app, ["init"])
    assert result.exit_code != 0
    # Either branch (upstream or local) prints the refuse + --force hint.
    assert "--force" in result.output


def test_init_force_overwrites_local(tmp_path, monkeypatch):
    """--force overwrites an existing local .aegis.py via the wizard."""
    _patch_claude_only(monkeypatch)
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".aegis.py").write_text("# old content\n")
    monkeypatch.setenv("HOME", str(tmp_path / "no_home"))

    # Wizard input: add agent (1=claude), pick model (1=opus),
    # permission (default=auto), effort (default=high), slug
    # (default=claude), done (option 2). No queues (n).
    stdin = "\n".join([
        "1",       # add agent → claude
        "1",       # model → opus
        "",        # permission → default auto
        "",        # effort → default high
        "",        # slug → default "claude"
        "2",       # done adding agents
        "n",       # no queues
    ]) + "\n"
    result = runner.invoke(app, ["init", "--force"], input=stdin)
    assert result.exit_code == 0, result.output
    written = (tmp_path / ".aegis.py").read_text()
    assert "Generated by `aegis init`" in written
    assert 'Agent(provider=ClaudeCode(' in written
    assert 'default_agent = "claude"' in written
    assert "# old content" not in written


def test_init_aborts_when_no_clis_detected(tmp_path, monkeypatch):
    """If detect_providers returns all-unavailable, abort cleanly."""
    monkeypatch.setattr(
        "aegis.init_wizard.detect_providers",
        lambda which=None: [
            ProviderSpec(
                name=n, cli=n, cls_name=c, model_shortlist=("x",),
                permission_choices=("auto",), default_permission="auto",
                has_effort=False, available=False)
            for (n, c) in (("claude-code", "ClaudeCode"),
                           ("gemini", "GeminiCLI"),
                           ("opencode", "OpenCode"))
        ])
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("HOME", str(tmp_path / "no_home"))
    result = runner.invoke(app, ["init"])
    assert result.exit_code != 0
    assert "No agent CLIs detected" in result.output


def test_init_writes_full_config_with_queue(tmp_path, monkeypatch):
    """End-to-end: add one agent, add one queue, write file, parse it."""
    _patch_claude_only(monkeypatch)
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("HOME", str(tmp_path / "no_home"))

    stdin = "\n".join([
        "1",       # add agent → claude
        "1",       # model → opus
        "",        # permission default
        "",        # effort default
        "",        # slug default "claude"
        "2",       # done agents
        "y",       # add queue
        "impl",    # queue name
        "1",       # bind to claude (only agent)
        "",        # max_parallel default 1
        "n",       # done queues
    ]) + "\n"
    result = runner.invoke(app, ["init"], input=stdin)
    assert result.exit_code == 0, result.output

    # Round-trip via the real config loader.
    from aegis.config import load_config, load_queues
    p = tmp_path / ".aegis.py"
    agents, default = load_config(search_paths=[p])
    assert default == "claude"
    assert set(agents) == {"claude"}
    qs = load_queues(p)
    assert set(qs) == {"impl"}
    assert qs["impl"].agent_profile == "claude"


def test_run_without_config_points_to_init(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("HOME", str(tmp_path))
    result = runner.invoke(app, [])
    assert result.exit_code != 0
    assert "aegis init" in result.output


def test_version_flag_prints_and_exits(tmp_path, monkeypatch):
    from importlib.metadata import version as _pkg_version
    monkeypatch.chdir(tmp_path)
    result = runner.invoke(app, ["--version"])
    assert result.exit_code == 0
    assert result.output.strip() == f"aegis {_pkg_version('aegis-harness')}"
