"""A Textual driver whose output is a byte sink rather than a terminal.

``WebDriver`` already frames its output as ``b"D" + length + ANSI`` through
``self._write``, which is an *instance* attribute (`web_driver.py:63`) and so
can be redirected per instance. That is what makes many views in one process
possible at all.

It is not sufficient on its own. ``WebDriver`` was written for exactly one
view attached to one process's stdout, and three other things in it are
process-global: it installs SIGINT/SIGTERM handlers on the running loop
(`:150-152`), it reads the process's real stdin (`:184`), and with
``size=None`` it takes its geometry from the ``COLUMNS``/``ROWS`` env vars
(`:52-59`). Each of those is fine for one view and wrong for N. It also
writes a ``__GANGLION__`` handshake line (`:154`) that nothing in aegis
consumes.
"""
from __future__ import annotations

from codecs import getincrementaldecoder
from threading import Event, Thread
from typing import Callable

from textual import events
from textual._xterm_parser import XTermParser
from textual.driver import Driver
from textual.drivers._byte_stream import ByteStream
from textual.drivers.web_driver import WebDriver, _ExitInput


class _NullInputReader:
    """Stands in for ``InputReader``, which binds stdin in its constructor.

    Only ``close()`` is ever called on it — by ``stop_application_mode``
    (`web_driver.py:181`).
    """

    def close(self) -> None:
        return


class ViewDriver(WebDriver):
    """One view's output, framed and handed to ``_sink``.

    Subclasses generated by :func:`view_driver_for` bind ``_sink``. The
    constructor signature is ``WebDriver``'s unchanged, because ``App``
    instantiates the class itself as
    ``driver_class(app, debug=…, mouse=…, size=…)`` (`app.py:3345-3350`)
    and there is no seam to pass anything else through.
    """

    #: Bound by ``view_driver_for``. A plain attribute rather than a
    #: constructor argument for the reason above.
    _sink: Callable[[bytes], None] = staticmethod(lambda _b: None)

    def __init__(self, app, *, debug: bool = False, mouse: bool = True,
                 size: tuple[int, int] | None = None) -> None:
        # NOT super(). WebDriver.__init__ binds this process's stdin and
        # stdout: it reads sys.__stdout__.fileno() (`:62`) and builds an
        # InputReader (`:68`) that registers sys.__stdin__ with a selector
        # in ITS constructor. Under systemd stdin is /dev/null, and
        # registering /dev/null with epoll raises PermissionError [Errno 1]
        # — so calling super() here makes the driver unbuildable in exactly
        # the daemon this stage exists to enable.
        #
        # So: Driver.__init__ for the real base state, then by hand the
        # seven attributes WebDriver.__init__ would have set. That couples
        # this to the BODY of a method we do not call;
        # test_every_attribute_webdriver_expects_is_present is the tripwire
        # for a Textual upgrade adding an eighth.
        Driver.__init__(self, app, debug=debug, mouse=mouse, size=size)
        self.stdout = None
        self.fileno = -1
        self.exit_event = Event()
        self._key_thread = Thread(target=lambda: None, name="view-noop")
        self._input_reader = _NullInputReader()
        self._deliveries: dict = {}
        self._write = self._emit

        # The input direction. WebDriver builds these inside
        # run_input_thread and holds them on the thread's stack
        # (`web_driver.py:186-191`); a fed driver has no thread, so they
        # are instance state. One set per view: XTermParser and the utf-8
        # decoder are both stateful across chunks, and a socket splits
        # wherever it likes -- mid-escape-sequence, mid-codepoint, and
        # mid-4-byte-length-header.
        self._byte_stream = ByteStream()
        self._parser = XTermParser(debug=self._debug)
        self._decode = getincrementaldecoder("utf-8")().decode

    def _emit(self, data: bytes) -> None:
        type(self)._sink(data)

    def feed(self, data: bytes) -> None:
        """Take a chunk of a client's stream. The input half of the seam.

        The body of ``WebDriver.run_input_thread`` (`web_driver.py:193-205`)
        without the thread: same ByteStream demux, same parser, same
        ``process_message``. Called on the event loop, so ``process_message``
        reaches ``App.post_message`` directly rather than across a thread.

        A damaged frame is swallowed per-frame rather than raised. The
        caller is a transport reading from an untrusted client, and every
        other view in this process shares one loop with it: a raise here
        would take down a socket task holding a view that did nothing
        wrong. ``_ExitInput`` is the one exception that must NOT be
        swallowed -- ``on_meta`` raises it for ``{"type": "exit"}``, which
        is the client saying it is gone.
        """
        for packet_type, payload in self._byte_stream.feed(data):
            if packet_type == "D":
                for event in self._parser.feed(self._decode(payload)):
                    self.process_message(event)
            else:
                try:
                    self._on_meta(packet_type, payload)
                except _ExitInput:
                    raise
                except Exception:  # noqa: BLE001 — see docstring
                    from traceback import format_exc

                    from textual import log
                    log(format_exc())
        for event in self._parser.tick():
            self.process_message(event)

    def start_application_mode(self) -> None:
        """Enter application mode without owning the process.

        Deliberately does NOT call ``super()``. Of what it does
        (`web_driver.py:150-173`) we keep the escape sequences and drop
        exactly four things, each for a stated reason:

        - the SIGINT/SIGTERM handlers (`:150-152`) — process-global, and N
          views on one loop means last-registration-wins;
        - the ``__GANGLION__`` handshake (`:154`) — nothing in aegis reads
          it, and a stage-5 attach client would see a malformed frame;
        - the Resize post (`:162-167`) — redundant, ``App`` dispatches its
          own from ``self.size`` (`app.py:3434`);
        - ``_key_thread.start()`` (`:172`) — there is no stdin to read.

        Everything else at `:169-173` is kept. ``_enable_bracketed_paste``
        in particular: without it a multi-line paste arrives as individual
        keystrokes, and since nothing in aegis/tui handles ``Paste`` today
        that degradation would be silent.
        """
        self.write("\x1b[?1049h")   # alt screen
        self._enable_mouse_support()
        self.write("\x1b[?25l")     # hide cursor
        self.write("\033[?1003h")   # mouse movement reporting
        self._request_terminal_sync_mode_support()
        self._enable_bracketed_paste()
        self.flush()
        self._app.call_later(self._app.post_message, events.AppBlur())

    def stop_application_mode(self) -> None:
        """Undo what ``start_application_mode`` did, then exit as WebDriver.

        `WebDriver.stop_application_mode` writes no escapes at all, which is
        right for a browser: the page tears the emulator down, so the modes
        die with it. A terminal is not a page. Detaching left the user's
        shell inside the alt screen, cursor hidden, mouse reporting still
        on, so every mouse movement printed escape sequences into their
        prompt.

        Nothing downstream can repair this. `aegis attach` restores termios,
        which is line discipline rather than terminal modes, and it is
        deliberately a dumb pipe that parses no frames and acts on no meta.
        The driver that turned these modes on is the only thing that knows
        they are on.

        Order follows `LinuxDriver.stop_application_mode`: paste and mouse
        off first, then leave the alt screen and show the cursor last, so
        the final state is written to the normal screen.
        """
        self._disable_bracketed_paste()
        self._disable_mouse_support()
        self.write("\x1b[?1049l")   # leave alt screen
        self.write("\x1b[?25h")     # show cursor
        self.flush()
        super().stop_application_mode()

    def run_input_thread(self) -> None:
        """No stdin. Input arrives through the transport, not the tty.

        Note this override is belt-and-braces, not the fix: the thread is
        only ever started by ``start_application_mode``, which we already
        replace. The real stdin fix is in ``__init__`` above.
        """
        return

    def disable_input(self) -> None:
        return


def view_driver_for(sink: Callable[[bytes], None]) -> type[ViewDriver]:
    """A ``ViewDriver`` subclass whose frames go to ``sink``."""
    return type("BoundViewDriver", (ViewDriver,),
                {"_sink": staticmethod(sink)})
