"""A Textual driver whose output is a byte sink rather than a terminal.

``WebDriver`` already frames its output as ``b"D" + length + ANSI`` through
``self._write``, which is an *instance* attribute (`web_driver.py:63`) and so
can be redirected per instance. That is what makes many views in one process
possible at all.

It is not sufficient on its own. ``WebDriver`` was written for exactly one
view attached to one process's stdout, and three other things in it are
process-global: it installs SIGINT/SIGTERM handlers on the running loop
(`:150-152`), it reads the process's real stdin (`:184`), and with
``size=None`` it takes its geometry from the ``COLUMNS``/``ROWS`` env vars
(`:52-59`). Each of those is fine for one view and wrong for N. It also
writes a ``__GANGLION__`` handshake line (`:154`) that nothing in aegis
consumes.
"""
from __future__ import annotations

from threading import Event, Thread
from typing import Callable

from textual import events
from textual.driver import Driver
from textual.drivers.web_driver import WebDriver


class _NullInputReader:
    """Stands in for ``InputReader``, which binds stdin in its constructor.

    Only ``close()`` is ever called on it — by ``stop_application_mode``
    (`web_driver.py:181`).
    """

    def close(self) -> None:
        return


class ViewDriver(WebDriver):
    """One view's output, framed and handed to ``_sink``.

    Subclasses generated by :func:`view_driver_for` bind ``_sink``. The
    constructor signature is ``WebDriver``'s unchanged, because ``App``
    instantiates the class itself as
    ``driver_class(app, debug=…, mouse=…, size=…)`` (`app.py:3345-3350`)
    and there is no seam to pass anything else through.
    """

    #: Bound by ``view_driver_for``. A plain attribute rather than a
    #: constructor argument for the reason above.
    _sink: Callable[[bytes], None] = staticmethod(lambda _b: None)

    def __init__(self, app, *, debug: bool = False, mouse: bool = True,
                 size: tuple[int, int] | None = None) -> None:
        # NOT super(). WebDriver.__init__ binds this process's stdin and
        # stdout: it reads sys.__stdout__.fileno() (`:62`) and builds an
        # InputReader (`:68`) that registers sys.__stdin__ with a selector
        # in ITS constructor. Under systemd stdin is /dev/null, and
        # registering /dev/null with epoll raises PermissionError [Errno 1]
        # — so calling super() here makes the driver unbuildable in exactly
        # the daemon this stage exists to enable.
        #
        # So: Driver.__init__ for the real base state, then by hand the
        # seven attributes WebDriver.__init__ would have set. That couples
        # this to the BODY of a method we do not call;
        # test_every_attribute_webdriver_expects_is_present is the tripwire
        # for a Textual upgrade adding an eighth.
        Driver.__init__(self, app, debug=debug, mouse=mouse, size=size)
        self.stdout = None
        self.fileno = -1
        self.exit_event = Event()
        self._key_thread = Thread(target=lambda: None, name="view-noop")
        self._input_reader = _NullInputReader()
        self._deliveries: dict = {}
        self._write = self._emit

    def _emit(self, data: bytes) -> None:
        type(self)._sink(data)

    def start_application_mode(self) -> None:
        """Enter application mode without owning the process.

        Deliberately does NOT call ``super()``. Of what it does
        (`web_driver.py:150-173`) we keep the escape sequences and drop
        exactly four things, each for a stated reason:

        - the SIGINT/SIGTERM handlers (`:150-152`) — process-global, and N
          views on one loop means last-registration-wins;
        - the ``__GANGLION__`` handshake (`:154`) — nothing in aegis reads
          it, and a stage-5 attach client would see a malformed frame;
        - the Resize post (`:162-167`) — redundant, ``App`` dispatches its
          own from ``self.size`` (`app.py:3434`);
        - ``_key_thread.start()`` (`:172`) — there is no stdin to read.

        Everything else at `:169-173` is kept. ``_enable_bracketed_paste``
        in particular: without it a multi-line paste arrives as individual
        keystrokes, and since nothing in aegis/tui handles ``Paste`` today
        that degradation would be silent.
        """
        self.write("\x1b[?1049h")   # alt screen
        self._enable_mouse_support()
        self.write("\x1b[?25l")     # hide cursor
        self.write("\033[?1003h")   # mouse movement reporting
        self._request_terminal_sync_mode_support()
        self._enable_bracketed_paste()
        self.flush()
        self._app.call_later(self._app.post_message, events.AppBlur())

    def run_input_thread(self) -> None:
        """No stdin. Input arrives through the transport, not the tty.

        Note this override is belt-and-braces, not the fix: the thread is
        only ever started by ``start_application_mode``, which we already
        replace. The real stdin fix is in ``__init__`` above.
        """
        return

    def disable_input(self) -> None:
        return


def view_driver_for(sink: Callable[[bytes], None]) -> type[ViewDriver]:
    """A ``ViewDriver`` subclass whose frames go to ``sink``."""
    return type("BoundViewDriver", (ViewDriver,),
                {"_sink": staticmethod(sink)})
