"""Install hook for socks-proxy: prompt for endpoint, generate the conf."""
from __future__ import annotations

import shutil

from aegis.plugins.install_context import InstallContext


CONF_BODY_TEMPLATE = """\
# Generated by the aegis socks-proxy plugin.
#
# Edit the [ProxyList] entry below to point at your SOCKS endpoint.
# To disable proxying without uninstalling the plugin, delete or rename
# this file — the pre_spawn hook becomes a no-op when it's absent.
#
# proxychains4 conf reference: https://github.com/rofl0r/proxychains-ng

strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
{endpoint}
"""

DEFAULT_ENDPOINT = "socks5 127.0.0.1 1080"


def _prompt_endpoint(ctx: InstallContext, default: str) -> str:
    if ctx._yes or ctx.console is None:
        return default
    from rich.prompt import Prompt
    return Prompt.ask(
        "SOCKS endpoint for proxychains "
        "(format: '<type> <host> <port>', e.g. 'socks5 127.0.0.1 1080')",
        default=default,
        console=ctx.console,
    )


def install(ctx: InstallContext) -> None:
    conf = ctx.aegis_dir / "socks-proxy.conf"
    conf.parent.mkdir(parents=True, exist_ok=True)

    default = ctx.manifest.get("default_config", {}).get(
        "endpoint", DEFAULT_ENDPOINT)

    if not conf.exists():
        endpoint = _prompt_endpoint(ctx, default)
        conf.write_text(
            CONF_BODY_TEMPLATE.format(endpoint=endpoint),
            encoding="utf-8",
        )

    if ctx.console is None:
        return
    msg = f"[green]socks-proxy[/] ready — conf at {conf}"
    if shutil.which("proxychains4") is None:
        msg += (
            "\n[yellow]warning:[/] proxychains4 not on PATH; harness "
            "spawns will fail until you install it "
            "(e.g. `apt install proxychains4`)."
        )
    msg += (
        f"\nDelete {conf} to disable proxying without uninstalling."
    )
    ctx.console.print(msg)
